import type { Track } from "./schema";

export type VibeTag =
  | "synthwave"
  | "lofi"
  | "jazz"
  | "ambient"
  | "indie"
  | "electronic"
  | "soul"
  | "folk";

export type SeedTrack = Track & { vibes: VibeTag[] };

export const MOCK_TRACKS: SeedTrack[] = [
  { title: "Neon Tide", artist: "Velvet Arcade", runtime: "3:42", vibes: ["synthwave"] },
  { title: "Chrome Pacific", artist: "Mirage Boulevard", runtime: "4:11", vibes: ["synthwave"] },
  { title: "Akihabara 3AM", artist: "Glass Cobra", runtime: "3:58", vibes: ["synthwave", "electronic"] },
  { title: "Hotel Saturn", artist: "Nightline Express", runtime: "5:02", vibes: ["synthwave"] },
  { title: "Pink Static", artist: "Replicant Avenue", runtime: "3:31", vibes: ["synthwave"] },
  { title: "Tokyo Driftwood", artist: "Vox Ouroboros", runtime: "4:24", vibes: ["synthwave"] },
  { title: "Highway 808", artist: "Mira Foxglove", runtime: "3:47", vibes: ["synthwave", "electronic"] },
  { title: "Last Cab Home", artist: "Pacific Honda", runtime: "4:09", vibes: ["synthwave"] },
  { title: "Holiday In Cobalt", artist: "Royal Sunwave", runtime: "3:55", vibes: ["synthwave"] },
  { title: "Magenta Skyline", artist: "Cassette Republic", runtime: "4:17", vibes: ["synthwave"] },
  { title: "Outrun The Sodium", artist: "Bay Bridge Ghosts", runtime: "3:38", vibes: ["synthwave"] },
  { title: "Polaroid Heart", artist: "Synth Saturn", runtime: "4:02", vibes: ["synthwave"] },
  { title: "Vapor Diner", artist: "Atlas Heron", runtime: "3:21", vibes: ["synthwave"] },
  { title: "Aphelion Drive", artist: "Plasma Boys", runtime: "5:14", vibes: ["synthwave"] },
  { title: "Pastel Fury", artist: "Yumiko Drift", runtime: "3:49", vibes: ["synthwave"] },
  { title: "Roomwide", artist: "Soft Static", runtime: "2:54", vibes: ["lofi"] },
  { title: "Rainy Bookshop", artist: "Kettle Society", runtime: "3:01", vibes: ["lofi"] },
  { title: "Plum Coffee", artist: "Goro Tanaka", runtime: "2:38", vibes: ["lofi", "jazz"] },
  { title: "Worn Cassette", artist: "Anjali Pine", runtime: "3:15", vibes: ["lofi"] },
  { title: "Notebook Margin", artist: "Slow Atlas", runtime: "2:47", vibes: ["lofi"] },
  { title: "Soft Lamp", artist: "Quiet Mode", runtime: "3:22", vibes: ["lofi"] },
  { title: "First Light", artist: "Park Bench Tapes", runtime: "2:59", vibes: ["lofi"] },
  { title: "Subway Dust", artist: "Indigo Bowl", runtime: "3:04", vibes: ["lofi"] },
  { title: "Window Seat", artist: "Marcel Adare", runtime: "3:30", vibes: ["lofi", "jazz"] },
  { title: "Late Library", artist: "Otis Mae", runtime: "2:51", vibes: ["lofi"] },
  { title: "Toast & Vinyl", artist: "June Solstice", runtime: "2:43", vibes: ["lofi"] },
  { title: "Linen Sky", artist: "Pocket Sun", runtime: "3:18", vibes: ["lofi"] },
  { title: "Apartment Plant", artist: "Greentea Quartet", runtime: "2:55", vibes: ["lofi", "jazz"] },
  { title: "Slow Bus", artist: "Hiraeth Audio", runtime: "3:10", vibes: ["lofi"] },
  { title: "Rolled Sleeves", artist: "Bookend Brothers", runtime: "2:48", vibes: ["lofi"] },
  { title: "Espresso Hours", artist: "Solene Fer", runtime: "3:33", vibes: ["lofi"] },
  { title: "Late Set, Marais", artist: "Augustin Vrede Quartet", runtime: "5:21", vibes: ["jazz"] },
  { title: "Brass Cathedral", artist: "Imani Otis Group", runtime: "6:04", vibes: ["jazz"] },
  { title: "Pickled Sevenths", artist: "The Marlow Trio", runtime: "4:18", vibes: ["jazz"] },
  { title: "Coltrane's Lighter", artist: "Bao Ngo Quintet", runtime: "7:11", vibes: ["jazz"] },
  { title: "Bossa for Mira", artist: "Renato Salles", runtime: "3:42", vibes: ["jazz"] },
  { title: "Sidecar Suite", artist: "Hattie Bloom Combo", runtime: "5:48", vibes: ["jazz"] },
  { title: "Velvet Backbeat", artist: "Cyrus Hwang", runtime: "4:33", vibes: ["jazz", "soul"] },
  { title: "Walking The Verge", artist: "Mavis Doune", runtime: "4:55", vibes: ["jazz"] },
  { title: "Vermouth & Rain", artist: "The Adair Six", runtime: "5:09", vibes: ["jazz"] },
  { title: "Indigo Hours", artist: "Sebastian Pell", runtime: "6:22", vibes: ["jazz"] },
  { title: "Two-Step Through Storyville", artist: "Otis Lemay Group", runtime: "4:47", vibes: ["jazz"] },
  { title: "Quiet Bell", artist: "Lior Asher", runtime: "5:30", vibes: ["jazz", "ambient"] },
  { title: "Half-Lit Avenue", artist: "Yoko Marin Trio", runtime: "4:12", vibes: ["jazz"] },
  { title: "Bridge In Three", artist: "Ruth Akala Quartet", runtime: "5:36", vibes: ["jazz"] },
  { title: "Late Hour Standard", artist: "Sam Rourke", runtime: "4:58", vibes: ["jazz"] },
  { title: "Glasslands", artist: "Aurelia Marsh", runtime: "7:21", vibes: ["ambient"] },
  { title: "Slow Tide Across Karelia", artist: "Vega Tundra", runtime: "8:42", vibes: ["ambient"] },
  { title: "Cathedral Of Air", artist: "Mira Loon", runtime: "6:14", vibes: ["ambient"] },
  { title: "Ember Fields", artist: "Hollow Lantern", runtime: "9:01", vibes: ["ambient"] },
  { title: "Sleeping Power Lines", artist: "North Boreal", runtime: "5:55", vibes: ["ambient"] },
  { title: "Snowfall, Inside", artist: "Cyan Atlas", runtime: "7:48", vibes: ["ambient"] },
  { title: "Linen Of Stars", artist: "Iver Holm", runtime: "6:33", vibes: ["ambient"] },
  { title: "Pale Lighthouse", artist: "Sava Vintar", runtime: "8:11", vibes: ["ambient"] },
  { title: "Underwater Garden", artist: "Aalto Pines", runtime: "7:09", vibes: ["ambient"] },
  { title: "Slow Window", artist: "Petra Skogen", runtime: "6:47", vibes: ["ambient"] },
  { title: "Static Meadow", artist: "Loris Vance", runtime: "5:24", vibes: ["ambient"] },
  { title: "Glacier Letters", artist: "Eira Hollow", runtime: "8:36", vibes: ["ambient"] },
  { title: "Hum Of Old Halls", artist: "Tomas Lind", runtime: "6:19", vibes: ["ambient"] },
  { title: "Soft Continent", artist: "Wilder Atlas", runtime: "7:02", vibes: ["ambient"] },
  { title: "Brittle Dawn", artist: "Anouk Vass", runtime: "6:50", vibes: ["ambient"] },
  { title: "House Plant Symphony", artist: "Field Bureau", runtime: "5:18", vibes: ["ambient"] },
  { title: "Stay Outside", artist: "Junie Halverson", runtime: "3:44", vibes: ["indie"] },
  { title: "Porch Smoke", artist: "Owen River Band", runtime: "4:12", vibes: ["indie", "folk"] },
  { title: "Soft Animals", artist: "Magdalena Foss", runtime: "3:51", vibes: ["indie"] },
  { title: "Bicycle Letter", artist: "Tatum Holloway", runtime: "3:28", vibes: ["indie"] },
  { title: "Bedroom Constellation", artist: "Hollow Sunday", runtime: "4:03", vibes: ["indie"] },
  { title: "Backseat Driving Lessons", artist: "Pen & Cole", runtime: "3:39", vibes: ["indie", "folk"] },
  { title: "Front Yard Choir", artist: "Almond Highway", runtime: "3:55", vibes: ["indie"] },
  { title: "Tape Hiss Love Song", artist: "Wren Adair", runtime: "3:46", vibes: ["indie"] },
  { title: "Diner Light", artist: "August River", runtime: "4:18", vibes: ["indie"] },
  { title: "Throwaway Year", artist: "Margot Sands", runtime: "3:24", vibes: ["indie"] },
  { title: "Wisteria Drive", artist: "Holiday For Marin", runtime: "3:57", vibes: ["indie"] },
  { title: "Couch Cathedral", artist: "Kirby Lane", runtime: "4:09", vibes: ["indie"] },
  { title: "Pollen Kitchen", artist: "Saoirse Pell", runtime: "3:33", vibes: ["indie"] },
  { title: "Late Bloomer", artist: "Beachgrass Mountain", runtime: "3:48", vibes: ["indie", "folk"] },
  { title: "Permanent Marker", artist: "Hazel Driver", runtime: "3:31", vibes: ["indie"] },
  { title: "Soft Spring", artist: "Lo & The Pines", runtime: "4:05", vibes: ["indie", "folk"] },
  { title: "Centrifuge", artist: "Object Permanence", runtime: "5:42", vibes: ["electronic"] },
  { title: "Trace Particle", artist: "Eos Subtle", runtime: "6:18", vibes: ["electronic"] },
  { title: "Black Loop", artist: "Drift Architect", runtime: "5:11", vibes: ["electronic"] },
  { title: "Hardware Heart", artist: "Cygnus Modular", runtime: "4:54", vibes: ["electronic"] },
  { title: "Concrete Bloom", artist: "Halcyon Voltage", runtime: "5:32", vibes: ["electronic"] },
  { title: "Bus Across Berlin", artist: "Nico Wand", runtime: "6:01", vibes: ["electronic"] },
  { title: "Vinyl Riot", artist: "Soft Reset", runtime: "4:38", vibes: ["electronic"] },
  { title: "Slow Burnaround", artist: "Mira Pulse", runtime: "5:15", vibes: ["electronic"] },
  { title: "Bandwidth For Tears", artist: "Yael Tributary", runtime: "4:42", vibes: ["electronic"] },
  { title: "After-Hours Lab", artist: "Boris Kovac", runtime: "6:24", vibes: ["electronic"] },
  { title: "Patch Cable Romance", artist: "Echo Tributary", runtime: "5:08", vibes: ["electronic"] },
  { title: "Garage Synth Sermon", artist: "Vance Modular", runtime: "4:49", vibes: ["electronic"] },
  { title: "Modular Sundown", artist: "Pavel Solano", runtime: "5:52", vibes: ["electronic"] },
  { title: "Quiet Modem", artist: "Atomic Coast", runtime: "4:26", vibes: ["electronic"] },
  { title: "Detuned Apology", artist: "Mira Pulse", runtime: "5:03", vibes: ["electronic"] },
  { title: "Glass Drum", artist: "Pneuma Drift", runtime: "5:36", vibes: ["electronic"] },
  { title: "Honey In Velvet", artist: "Ruth Faro", runtime: "4:17", vibes: ["soul"] },
  { title: "Heart In The Mail", artist: "Otis & The Hollow", runtime: "3:48", vibes: ["soul"] },
  { title: "Slow Train Sunday", artist: "Mavis Kane", runtime: "4:32", vibes: ["soul"] },
  { title: "Cinnamon Telephone", artist: "Lee Cordero", runtime: "3:54", vibes: ["soul"] },
  { title: "Brass Door", artist: "Imani Holt", runtime: "4:09", vibes: ["soul"] },
  { title: "Backbeat Apology", artist: "Junior Maitland", runtime: "3:41", vibes: ["soul"] },
  { title: "Cocoa Streetlight", artist: "Marisol Vega", runtime: "4:21", vibes: ["soul"] },
  { title: "Sunday Hymn, Detuned", artist: "Ezra Cole", runtime: "4:48", vibes: ["soul"] },
  { title: "Slowdance Of The Boroughs", artist: "Niko Aurelius", runtime: "5:02", vibes: ["soul"] },
  { title: "Soft Margin", artist: "The Vella Letters", runtime: "3:37", vibes: ["soul"] },
  { title: "Velvet Receipt", artist: "Anaya Brooks", runtime: "4:11", vibes: ["soul"] },
  { title: "Brown Sugar Light", artist: "Otis Marin", runtime: "3:53", vibes: ["soul"] },
  { title: "Choir Of Forgotten Bells", artist: "Sade Kennedy", runtime: "5:19", vibes: ["soul"] },
  { title: "Slowest Yes", artist: "June Hollander", runtime: "4:02", vibes: ["soul"] },
  { title: "Coral Apartment", artist: "Wesley Pell", runtime: "4:27", vibes: ["soul"] },
  { title: "Sugar In The Lamp", artist: "Mavis Kane", runtime: "3:46", vibes: ["soul"] },
  { title: "Driftwood Letter", artist: "Wren Hallow", runtime: "3:32", vibes: ["folk"] },
  { title: "Plum Cabin", artist: "Holiday For Marin", runtime: "3:58", vibes: ["folk"] },
  { title: "Old Atlas Of Home", artist: "Ezra Vince", runtime: "4:11", vibes: ["folk"] },
  { title: "Wool Hours", artist: "Magpie & Mae", runtime: "3:42", vibes: ["folk"] },
  { title: "Slow Field", artist: "Junie Halverson", runtime: "3:24", vibes: ["folk", "indie"] },
  { title: "Hymn For The Train", artist: "Augustin Vrede", runtime: "4:05", vibes: ["folk"] },
  { title: "Brittle Pine", artist: "Sava Vintar", runtime: "3:51", vibes: ["folk"] },
  { title: "Letter Home, Stamped", artist: "Otis Mae", runtime: "3:37", vibes: ["folk"] },
  { title: "Rain Pail", artist: "Bookend Brothers", runtime: "3:48", vibes: ["folk"] },
  { title: "Frost On The Windowsill", artist: "Saoirse Pell", runtime: "4:18", vibes: ["folk"] },
  { title: "Cinder Apology", artist: "Margot Sands", runtime: "3:29", vibes: ["folk"] },
  { title: "Long Road, Short Lamp", artist: "Wren Adair", runtime: "4:01", vibes: ["folk"] },
  { title: "Almond Tree Letter", artist: "Hattie Bloom", runtime: "3:55", vibes: ["folk"] },
  { title: "Pewter Sky", artist: "Iver Holm", runtime: "4:22", vibes: ["folk", "ambient"] },
  { title: "Beachgrass Morning", artist: "Owen River Band", runtime: "3:47", vibes: ["folk"] },
  { title: "Quiet Threshold", artist: "Lo & The Pines", runtime: "4:08", vibes: ["folk"] },
  { title: "Cassette Tide", artist: "Velvet Arcade", runtime: "4:00", vibes: ["synthwave"] },
  { title: "Sun Through Slats", artist: "Park Bench Tapes", runtime: "2:52", vibes: ["lofi"] },
  { title: "Twelve Bar Letter", artist: "Mavis Doune", runtime: "5:13", vibes: ["jazz"] },
  { title: "Slow Glass Window", artist: "Hollow Lantern", runtime: "7:38", vibes: ["ambient"] },
  { title: "Cassette Yard", artist: "Tatum Holloway", runtime: "3:35", vibes: ["indie"] },
  { title: "Subwoofer Cathedral", artist: "Object Permanence", runtime: "5:47", vibes: ["electronic"] },
  { title: "Velvet Receipt II", artist: "Anaya Brooks", runtime: "4:18", vibes: ["soul"] },
  { title: "Slow Field, Returning", artist: "Junie Halverson", runtime: "3:29", vibes: ["folk"] },
  { title: "Tangerine Static", artist: "Mirage Boulevard", runtime: "3:46", vibes: ["synthwave"] },
  { title: "Toaster Window", artist: "Quiet Mode", runtime: "2:48", vibes: ["lofi"] },
  { title: "Blue Note Reverie", artist: "Imani Otis Group", runtime: "5:33", vibes: ["jazz"] },
  { title: "Glacial Postcard", artist: "Vega Tundra", runtime: "8:09", vibes: ["ambient"] },
  { title: "Sticker On A Bumper", artist: "Almond Highway", runtime: "3:41", vibes: ["indie"] },
  { title: "Loop Of Honey", artist: "Eos Subtle", runtime: "5:24", vibes: ["electronic"] },
  { title: "Coffee Shop Hymn", artist: "Ezra Cole", runtime: "4:02", vibes: ["soul"] },
  { title: "Two Suitcases", artist: "Wren Hallow", runtime: "3:38", vibes: ["folk"] },
  { title: "Akihabara Subway", artist: "Glass Cobra", runtime: "4:14", vibes: ["synthwave"] },
  { title: "Pile Of Old Books", artist: "Goro Tanaka", runtime: "2:55", vibes: ["lofi"] },
  { title: "Standard For Mira", artist: "The Marlow Trio", runtime: "4:46", vibes: ["jazz"] },
  { title: "Tundra Window", artist: "North Boreal", runtime: "6:48", vibes: ["ambient"] },
  { title: "Frontyard Choirboy", artist: "Pen & Cole", runtime: "3:31", vibes: ["indie"] },
  { title: "Square Wave Sermon", artist: "Drift Architect", runtime: "5:09", vibes: ["electronic"] },
  { title: "Late Letter, Sunday", artist: "Lee Cordero", runtime: "4:20", vibes: ["soul"] },
  { title: "Boots In The Snow", artist: "Magpie & Mae", runtime: "3:44", vibes: ["folk"] },
  { title: "Cherry Blossom Static", artist: "Yumiko Drift", runtime: "3:33", vibes: ["synthwave"] },
  { title: "Hammock Hour", artist: "Pocket Sun", runtime: "3:11", vibes: ["lofi"] },
  { title: "Slow Train, Trio", artist: "Hattie Bloom Combo", runtime: "5:01", vibes: ["jazz"] },
  { title: "Linen Drift", artist: "Cyan Atlas", runtime: "7:32", vibes: ["ambient"] },
  { title: "Knees On The Dashboard", artist: "Owen River Band", runtime: "3:48", vibes: ["indie"] },
  { title: "Modular Pastoral", artist: "Cygnus Modular", runtime: "5:21", vibes: ["electronic"] },
  { title: "Cathedral Bassline", artist: "Imani Holt", runtime: "4:38", vibes: ["soul"] },
  { title: "Long Lamp", artist: "Augustin Vrede", runtime: "3:54", vibes: ["folk"] },
  { title: "Outrun The Sodium II", artist: "Bay Bridge Ghosts", runtime: "3:48", vibes: ["synthwave"] },
  { title: "Bedroom Window, Open", artist: "Anjali Pine", runtime: "3:09", vibes: ["lofi"] },
  { title: "Coltrane's Other Lighter", artist: "Bao Ngo Quintet", runtime: "6:55", vibes: ["jazz"] },
  { title: "Boreal Pulse", artist: "Aalto Pines", runtime: "7:18", vibes: ["ambient"] },
  { title: "Couch Cathedral II", artist: "Kirby Lane", runtime: "4:01", vibes: ["indie"] },
  { title: "Quiet Modem II", artist: "Atomic Coast", runtime: "4:32", vibes: ["electronic"] },
  { title: "Brass Door, Open", artist: "Imani Holt", runtime: "4:14", vibes: ["soul"] },
  { title: "Frost Field, Walking", artist: "Iver Holm", runtime: "4:09", vibes: ["folk"] },
  { title: "Polaroid Heart, Faded", artist: "Synth Saturn", runtime: "4:15", vibes: ["synthwave"] },
  { title: "Window In Winter", artist: "Slow Atlas", runtime: "2:51", vibes: ["lofi"] },
  { title: "Bossa, Returning", artist: "Renato Salles", runtime: "3:51", vibes: ["jazz"] },
  { title: "Ember Fields II", artist: "Hollow Lantern", runtime: "8:42", vibes: ["ambient"] },
  { title: "Tape Hiss Apology", artist: "Wren Adair", runtime: "3:39", vibes: ["indie"] },
  { title: "Modular Saturday", artist: "Pavel Solano", runtime: "5:44", vibes: ["electronic"] },
  { title: "Choir Of Forgotten Bells II", artist: "Sade Kennedy", runtime: "5:08", vibes: ["soul"] },
  { title: "Almond Tree, Stamped", artist: "Hattie Bloom", runtime: "3:50", vibes: ["folk"] },
  { title: "Magenta Skyline, Reprise", artist: "Cassette Republic", runtime: "4:23", vibes: ["synthwave"] },
  { title: "Notebook Margin II", artist: "Slow Atlas", runtime: "2:42", vibes: ["lofi"] },
  { title: "Two-Step Through Storyville II", artist: "Otis Lemay Group", runtime: "4:51", vibes: ["jazz"] },
  { title: "Glasslands, Returning", artist: "Aurelia Marsh", runtime: "7:08", vibes: ["ambient"] },
  { title: "Front Yard Choir II", artist: "Almond Highway", runtime: "3:58", vibes: ["indie"] },
  { title: "Patch Cable Letter", artist: "Echo Tributary", runtime: "5:14", vibes: ["electronic"] },
  { title: "Velvet Receipt III", artist: "Anaya Brooks", runtime: "4:09", vibes: ["soul"] },
  { title: "Rain Pail, Returning", artist: "Bookend Brothers", runtime: "3:51", vibes: ["folk"] },
  { title: "Highway 808 II", artist: "Mira Foxglove", runtime: "3:55", vibes: ["synthwave"] },
  { title: "Apartment Plant II", artist: "Greentea Quartet", runtime: "3:02", vibes: ["lofi"] },
  { title: "Pickled Sevenths II", artist: "The Marlow Trio", runtime: "4:25", vibes: ["jazz"] },
  { title: "Soft Continent II", artist: "Wilder Atlas", runtime: "7:14", vibes: ["ambient"] },
  { title: "Bedroom Constellation II", artist: "Hollow Sunday", runtime: "4:09", vibes: ["indie"] },
  { title: "Hardware Heart II", artist: "Cygnus Modular", runtime: "5:01", vibes: ["electronic"] },
  { title: "Sugar In The Lamp II", artist: "Mavis Kane", runtime: "3:54", vibes: ["soul"] },
  { title: "Old Atlas Of Home II", artist: "Ezra Vince", runtime: "4:18", vibes: ["folk"] },
  { title: "Chrome Pacific II", artist: "Mirage Boulevard", runtime: "4:01", vibes: ["synthwave"] },
  { title: "Rainy Bookshop II", artist: "Kettle Society", runtime: "3:14", vibes: ["lofi"] },
  { title: "Late Hour Standard II", artist: "Sam Rourke", runtime: "5:08", vibes: ["jazz"] },
  { title: "Pale Lighthouse II", artist: "Sava Vintar", runtime: "8:34", vibes: ["ambient"] },
  { title: "Throwaway Year II", artist: "Margot Sands", runtime: "3:31", vibes: ["indie"] },
  { title: "After-Hours Lab II", artist: "Boris Kovac", runtime: "6:09", vibes: ["electronic"] },
  { title: "Honey In Velvet II", artist: "Ruth Faro", runtime: "4:21", vibes: ["soul"] },
  { title: "Pewter Sky II", artist: "Iver Holm", runtime: "4:32", vibes: ["folk"] },
  { title: "Aphelion Drive II", artist: "Plasma Boys", runtime: "5:21", vibes: ["synthwave"] },
  { title: "Toast & Vinyl II", artist: "June Solstice", runtime: "2:55", vibes: ["lofi"] },
  { title: "Walking The Verge II", artist: "Mavis Doune", runtime: "5:11", vibes: ["jazz"] },
  { title: "Cathedral Of Air II", artist: "Mira Loon", runtime: "6:32", vibes: ["ambient"] },
  { title: "Wisteria Drive II", artist: "Holiday For Marin", runtime: "4:02", vibes: ["indie"] },
  { title: "Trace Particle II", artist: "Eos Subtle", runtime: "6:01", vibes: ["electronic"] },
  { title: "Slowdance II", artist: "Niko Aurelius", runtime: "4:48", vibes: ["soul"] },
  { title: "Letter Home, Returned", artist: "Otis Mae", runtime: "3:42", vibes: ["folk"] },
  { title: "Pastel Fury II", artist: "Yumiko Drift", runtime: "3:55", vibes: ["synthwave"] },
];

const VIBE_KEYWORDS: Record<VibeTag, string[]> = {
  synthwave: ["synthwave", "neon", "tokyo", "drive", "night", "retro", "cyber", "vapor", "80s", "cassette"],
  lofi: ["lofi", "lo-fi", "study", "coffee", "rain", "chill", "sunday", "espresso", "morning", "soft"],
  jazz: ["jazz", "saxophone", "bossa", "swing", "blue", "smoky", "bar", "trio", "quartet", "noir"],
  ambient: ["ambient", "drone", "slow", "spacious", "calm", "glacial", "field", "sleep", "snow", "fog"],
  indie: ["indie", "bedroom", "bicycle", "porch", "yard", "earnest", "summer", "diary", "first", "love"],
  electronic: ["electronic", "techno", "dance", "club", "modular", "warehouse", "berlin", "synth", "beat"],
  soul: ["soul", "motown", "honey", "velvet", "brass", "groove", "warm", "sunday", "church", "lover"],
  folk: ["folk", "acoustic", "cabin", "field", "letter", "home", "winter", "fire", "country", "porch"],
};

export function inferVibeTags(input: string): VibeTag[] {
  const lower = input.toLowerCase();
  const hits = new Set<VibeTag>();
  for (const [tag, words] of Object.entries(VIBE_KEYWORDS) as [VibeTag, string[]][]) {
    if (words.some((w) => lower.includes(w))) hits.add(tag);
  }
  return [...hits];
}

export function pickTracksForVibe(vibe: string, count = 8): Track[] {
  const tags = inferVibeTags(vibe);
  const matched = tags.length
    ? MOCK_TRACKS.filter((t) => t.vibes.some((v) => tags.includes(v)))
    : MOCK_TRACKS;
  const pool = matched.length >= count ? matched : MOCK_TRACKS;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map(({ title, artist, runtime }) => ({ title, artist, runtime }));
}
